export const setUserToken = 'setUserToken'
export const setUser = 'setUser'
export const logout = 'logout'
export const setSections = 'setSections'
export const setAccounts = 'setAccounts'
export const addAlertTop = 'addAlertTop'
export const removeAlretTop = 'removeAlretTop'
